[package]
name = "bio-jtools"
version = "2019.2.10"
authors = ["James Hawley <jamesrichardhawley@gmail.com>"]
edition = "2018"
description = "A suite of bioinformatics tools for interacting with high throughput sequencing (HTS) data"
license = "MIT"
repository = "https://github.com/jrhawley/bio-jtools-rs/"
homepage = "https://github.com/jrhawley/bio-jtools-rs/"
readme = "README.md"
categories = ["command-line-utilities", "science"]

[dependencies]
bio = "0.30.0"
fastq = "0.6.0"

[dependencies.clap]
version = "2"
default-features = true
features = [ "yaml" ]