[package]
name = "bio-jtools"
version = "2020.5.31"
authors = ["James Hawley <jamesrichardhawley@gmail.com>"]
edition = "2018"
description = "A suite of bioinformatics tools for interacting with high throughput sequencing (HTS) data"
license = "MIT"
repository = "https://github.com/jrhawley/bio-jtools-rs/"
homepage = "https://github.com/jrhawley/bio-jtools-rs/"
readme = "README.md"
categories = ["command-line-utilities", "science"]
keywords = ["bioinformatics", "cli", "fastq"]
include = [
	"src/**/*",
	"Cargo.toml",
	"README.md"
]

[dependencies]
bio = "0.30.0"
needletail = "0.3.2"
chrono = "0.4.11"
regex = "1.3.9"
walkdir = "2.3.1"

[dependencies.clap]
version = "2"
default-features = true
features = [ "yaml" ]

[[bin]]
name = "bjt"
path = "src/main.rs"

