[package]
name = "bio-jtools"
version = "0.1.0"
authors = ["James Hawley <jamesrichardhawley@gmail.com>"]
edition = "2018"
description = "A suite of bioinformatics tools for personal use"

[dependencies.clap]
version = "2"
default-features = true
features = [ "yaml" ]